### ISSUE TITLE
ONSPAudioSource, are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by ItzDragonFace** [vrchat-community/ClientSim#19] opened 2022-04-21 00:51 UTC
Assets\com.vrchat.ClientSim\Runtime\Helpers\ClientSimSpatialAudioHelper.cs(8,48): error CS0246: The type or namespace name 'ONSPAudioSource' could not be found (are you missing a using directive or an assembly reference?)

Assets\com.vrchat.ClientSim\Runtime\Helpers\ClientSimSpatialAudioHelper.cs(15,17): error CS0246: The type or namespace name 'ONSPAudioSource' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Toxic-Cookie** [comment] 2022-05-14 00:11
I'm also getting this error. Is there any solution?

**Comment by Enverex** [comment] 2022-05-29 16:59
Are you using the GIT repo version of the SDK or the downloaded one? I had this same error when using the downloaded SDK rather than the GIT one.

**Comment by momo-the-monster** [comment] 2023-01-11 16:41
This appears to be a duplicate of #6, which should no longer be an issue - let me know if it's still happening for you @ItzDragonFace @Toxic-Cookie!

**Closed** 2023-01-16 17:37 UTC
Labels: duplicate
