### ISSUE TITLE
Error after package import

### ISSUE THREAD

**Issue by Adam-Kay** [vrchat-community/ClientSim#14] opened 2022-04-01 16:48 UTC
### Description:
Got a couple of errors right after importing this. Saw it was in the library folder so I tried closing the project, deleting Library and restarting but the same error occurs instantly.
![image](https://user-images.githubusercontent.com/10010491/161306620-58a8580b-819a-4a2a-ad4d-7e099b995556.png)

#### 1
```
Library\PackageCache\com.vrchat.clientsim@042856263b\Runtime\Helpers\ClientSimSpatialAudioHelper.cs(8,48): error CS0246: 
The type or namespace name 'ONSPAudioSource' could not be found (are you missing a using directive or an assembly reference?)
```

#### 2
```
Library\PackageCache\com.vrchat.clientsim@042856263b\Runtime\Helpers\ClientSimSpatialAudioHelper.cs(15,17): error CS0246:
The type or namespace name 'ONSPAudioSource' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by momo-the-monster** [comment] 2022-04-02 00:26
Sounds like a duplicate of #6 - please search issues before filing a new one, thanks!

**Closed by momo-the-monster** 2022-04-02 00:26 UTC
Labels: duplicate
